-- news-portal "CLEAN REBUILD" Script (Identity Native)
-- Run this in pgAdmin (postgres database) to reset everything.

-- 1. CLEANUP: Delete everything existing first
DROP TABLE IF EXISTS "Articles", "Categories", "ChatMessages", "ContactSubmissions", "Pages", "Users", "Roles", "UserClaims", "UserRoles", "UserLogins", "RoleClaims", "UserTokens", "__EFMigrationsHistory" CASCADE;

-- 2. CREATE SCHEMA (Identity Tables First)

CREATE TABLE "Users" (
    "Id" uuid NOT NULL DEFAULT gen_random_uuid(),
    "UserName" text,
    "NormalizedUserName" text,
    "Email" text,
    "NormalizedEmail" text,
    "EmailConfirmed" boolean NOT NULL DEFAULT FALSE,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL DEFAULT FALSE,
    "TwoFactorEnabled" boolean NOT NULL DEFAULT FALSE,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL DEFAULT FALSE,
    "AccessFailedCount" integer NOT NULL DEFAULT 0,
    -- Custom Fields
    "FullName" text,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "PublicKey" text NOT NULL DEFAULT '',
    "PrivateKey" text NOT NULL DEFAULT '',
    "ProfileImage" text,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "Roles" (
    "Id" uuid NOT NULL DEFAULT gen_random_uuid(),
    "Name" text,
    "NormalizedName" text,
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);

CREATE TABLE "UserRoles" (
    "UserId" uuid NOT NULL,
    "RoleId" uuid NOT NULL,
    CONSTRAINT "PK_UserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_UserRoles_Roles" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserRoles_Users" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_UserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserClaims_Users" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_UserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_UserLogins_Users" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserTokens" (
    "UserId" uuid NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_UserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_UserTokens_Users" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "RoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_RoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RoleClaims_Roles" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
);

-- Application Tables

CREATE TABLE "Categories" (
    "Id" uuid NOT NULL DEFAULT gen_random_uuid(),
    "Name" text NOT NULL,
    CONSTRAINT "PK_Categories" PRIMARY KEY ("Id")
);

CREATE TABLE "Articles" (
    "Id" uuid NOT NULL DEFAULT gen_random_uuid(),
    "Title" text NOT NULL,
    "Content" text NOT NULL,
    "Excerpt" text,
    "Author" text NOT NULL,
    "CategoryId" uuid, -- Normalized Foreign Key
    "PublishedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "ImageUrl" text,
    "ViewCount" integer NOT NULL DEFAULT 0,
    "IsTrending" boolean NOT NULL DEFAULT FALSE,
    "IsFeatured" boolean NOT NULL DEFAULT FALSE,
    "IsEditorsPick" boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT "PK_Articles" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Articles_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE SET NULL
);

CREATE TABLE "ChatMessages" (
    "Id" uuid NOT NULL DEFAULT gen_random_uuid(),
    "SenderUserId" uuid NOT NULL,
    "ReceiverUserId" uuid NOT NULL,
    "Content" text NOT NULL,
    "Timestamp" timestamp with time zone NOT NULL DEFAULT now(),
    "IsRead" boolean NOT NULL DEFAULT FALSE,
    "IsDeleted" boolean NOT NULL DEFAULT FALSE,
    "DeletedFor" text DEFAULT '',
    CONSTRAINT "PK_ChatMessages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ChatMessages_Users_Sender" FOREIGN KEY ("SenderUserId") REFERENCES "Users" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ChatMessages_Users_Receiver" FOREIGN KEY ("ReceiverUserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ContactSubmissions" (
    "Id" uuid NOT NULL DEFAULT gen_random_uuid(),
    "Name" text NOT NULL,
    "Email" text NOT NULL,
    "Phone" text NOT NULL,
    "Message" text NOT NULL,
    "SubmittedAt" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_ContactSubmissions" PRIMARY KEY ("Id")
);

CREATE TABLE "Pages" (
    "Slug" text NOT NULL,
    "Title" text NOT NULL,
    "Body" text NOT NULL,
    "LastUpdated" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_Pages" PRIMARY KEY ("Slug")
);

CREATE TABLE "Comments" (
    "Id" uuid NOT NULL,
    "ArticleId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Content" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_Comments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Comments_Articles_ArticleId" FOREIGN KEY ("ArticleId") REFERENCES "Articles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Comments_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

-- 3. Indexes

CREATE INDEX "IX_Users_NormalizedUserName" ON "Users" ("NormalizedUserName");
CREATE INDEX "IX_Users_NormalizedEmail" ON "Users" ("NormalizedEmail");
CREATE INDEX "IX_Roles_NormalizedName" ON "Roles" ("NormalizedName");
CREATE INDEX "IX_UserRoles_RoleId" ON "UserRoles" ("RoleId");
CREATE INDEX "IX_UserClaims_UserId" ON "UserClaims" ("UserId");
CREATE INDEX "IX_UserLogins_UserId" ON "UserLogins" ("UserId");
CREATE INDEX "IX_RoleClaims_RoleId" ON "RoleClaims" ("RoleId");

CREATE INDEX "IX_Articles_CategoryId" ON "Articles" ("CategoryId");
CREATE INDEX "IX_Articles_PublishedAt" ON "Articles" ("PublishedAt");
CREATE INDEX "IX_Articles_IsTrending" ON "Articles" ("IsTrending");
CREATE INDEX "IX_Articles_IsFeatured" ON "Articles" ("IsFeatured");
CREATE INDEX "IX_Articles_IsEditorsPick" ON "Articles" ("IsEditorsPick");
CREATE INDEX "IX_ChatMessages_SenderUserId" ON "ChatMessages" ("SenderUserId");
CREATE INDEX "IX_ChatMessages_ReceiverUserId" ON "ChatMessages" ("ReceiverUserId");
CREATE INDEX "IX_ContactSubmissions_SubmittedAt" ON "ContactSubmissions" ("SubmittedAt");
CREATE INDEX "IX_Comments_ArticleId" ON "Comments" ("ArticleId");
CREATE INDEX "IX_Comments_UserId" ON "Comments" ("UserId");

-- 4. Seed Data (Categories Only - Users/Roles/Admin handled by C# Seeding)
INSERT INTO "Categories" ("Name")
SELECT 'World' WHERE NOT EXISTS (SELECT 1 FROM "Categories" WHERE "Name" = 'World');
INSERT INTO "Categories" ("Name")
SELECT 'Business' WHERE NOT EXISTS (SELECT 1 FROM "Categories" WHERE "Name" = 'Business');
INSERT INTO "Categories" ("Name")
SELECT 'Technology' WHERE NOT EXISTS (SELECT 1 FROM "Categories" WHERE "Name" = 'Technology');
INSERT INTO "Categories" ("Name")
SELECT 'Sports' WHERE NOT EXISTS (SELECT 1 FROM "Categories" WHERE "Name" = 'Sports');
INSERT INTO "Categories" ("Name")
SELECT 'Health' WHERE NOT EXISTS (SELECT 1 FROM "Categories" WHERE "Name" = 'Health');
INSERT INTO "Categories" ("Name")
SELECT 'Entertainment' WHERE NOT EXISTS (SELECT 1 FROM "Categories" WHERE "Name" = 'Entertainment');
INSERT INTO "Categories" ("Name")
SELECT 'Science' WHERE NOT EXISTS (SELECT 1 FROM "Categories" WHERE "Name" = 'Science');
