-- news-portal "CLEAN REBUILD" Script
-- Run this in pgAdmin (postgres database, port 5433) to reset everything.

-- 1. CLEANUP: Delete everything existing first
DROP TABLE IF EXISTS "Articles", "Categories", "ChatMessages", "ContactSubmissions", "Pages", "Users", "__EFMigrationsHistory" CASCADE;

-- 2. CREATE SCHEMA
CREATE TABLE "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

-- Articles Table
CREATE TABLE "Articles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Category" text NOT NULL,
    "Title" text NOT NULL,
    "Excerpt" text NOT NULL,
    "Author" text NOT NULL,
    "ImageUrl" text NOT NULL,
    "Content" text NOT NULL,
    "IsTrending" boolean NOT NULL DEFAULT FALSE,
    "PublishedAt" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_Articles" PRIMARY KEY ("Id")
);

-- Categories Table (with UNIQUE constraint needed for ON CONFLICT)
CREATE TABLE "Categories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL UNIQUE,
    CONSTRAINT "PK_Categories" PRIMARY KEY ("Id")
);

-- ChatMessages Table
CREATE TABLE "ChatMessages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SenderUserId" integer NOT NULL,
    "ReceiverUserId" integer NOT NULL,
    "Content" text NOT NULL,
    "Timestamp" timestamp with time zone NOT NULL DEFAULT now(),
    "IsRead" boolean NOT NULL DEFAULT FALSE,
    "DeletedFor" text NOT NULL DEFAULT '',
    CONSTRAINT "PK_ChatMessages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ChatMessages_Sender" FOREIGN KEY ("SenderUserId") REFERENCES "Users" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ChatMessages_Receiver" FOREIGN KEY ("ReceiverUserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

-- ContactSubmissions Table
CREATE TABLE "ContactSubmissions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Email" text NOT NULL,
    "Phone" text NOT NULL DEFAULT '',
    "Message" text NOT NULL,
    "SubmittedAt" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_ContactSubmissions" PRIMARY KEY ("Id")
);

-- Pages Table (with UNIQUE constraint needed for ON CONFLICT)
CREATE TABLE "Pages" (
    "Slug" text NOT NULL UNIQUE,
    "Title" text NOT NULL,
    "Body" text NOT NULL,
    "LastUpdated" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_Pages" PRIMARY KEY ("Slug")
);

-- Users Table (with UNIQUE constraint needed for ON CONFLICT)
CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Username" text NOT NULL UNIQUE,
    "PasswordHash" text NOT NULL,
    "Role" text NOT NULL,
    "Email" text,
    "FullName" text,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "PublicKey" text NOT NULL DEFAULT '',
    "PrivateKey" text NOT NULL DEFAULT '',
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

-- 3. Performance Indexes
CREATE INDEX "IX_Articles_Category" ON "Articles" ("Category");
CREATE INDEX "IX_Articles_PublishedAt" ON "Articles" ("PublishedAt");
CREATE INDEX "IX_Articles_IsTrending" ON "Articles" ("IsTrending");
CREATE INDEX "IX_Users_Role" ON "Users" ("Role");

-- 4. Seed Data
-- This now works because the UNIQUE constraints were created above
INSERT INTO "Categories" ("Name")
VALUES ('World'), ('Business'), ('Technology'), ('Sports'), ('Entertainment')
ON CONFLICT ("Name") DO NOTHING;

INSERT INTO "Pages" ("Slug", "Title", "Body")
VALUES 
('about', 'About Us', 'Welcome to Khabar Manch...'),
('careers', 'Careers', 'We are currently fully staffed...')
ON CONFLICT ("Slug") DO NOTHING;

INSERT INTO "Users" ("Username", "PasswordHash", "Role", "FullName")
VALUES ('Admin', 'Admin@5175', 'Admin', 'Narine Bhattarai')
ON CONFLICT ("Username") DO NOTHING;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260107214704_InitialSupabaseSchema', '8.0.0')
ON CONFLICT ("MigrationId") DO NOTHING;

COMMIT;
